services:
  api-core-info:
    image: api-core-info
    container_name: api-core-info
    build:
      context: .
      dockerfile: ./apps/core/Dockerfile
    restart: unless-stopped
    command: >
        sh -c "npm run migrate && npm run seed:all && npm run start:dev core"
    env_file:
      - .env
    ports:
      - '3340:80' # host:container
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: development
      API_PORT: 80
      DB_HOST: postgres
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - network
    volumes:
      - .:/usr/src/app

  postgres:
    container_name: info_postgres
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    ports:
      - '5434:5432'
    volumes:
      - ./.docker_volumes:/var/lib/postgresql/data/
    networks:
      - network

networks:
  network:
    driver: bridge
